apiVersion: v1
kind: Namespace
metadata:
  name: pulseboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulseboard-api
  namespace: pulseboard
  labels:
    app: pulseboard-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulseboard-api
  template:
    metadata:
      labels:
        app: pulseboard-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: api
        image: pulseboard-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pulseboard-api
  namespace: pulseboard
spec:
  selector:
    app: pulseboard-api
  ports:
  - port: 80
    targetPort: 8000